<?php $this->layout()->setLayout('second_layout'); ?>
<div class="col-md-12">
<div class="panel panel-primary">
    <div class="panel-heading">List of Addresses for this Customer</div>
    <div class="panel-body">
<?php if($this->data) { ?>
<form action="<?php echo $this->baseUrl()?>/shipping/update/reg_id/<?php echo $this->reg_id?>" method="post" onsubmit="return confirm('Are you sure you want to submit this form?');">
<table>
    <tr>
        <th>First Name</th>
        <th>Last Name</th>
        <th>Address</th>
        <th>City</th>
        <th>State</th>
        <th>Zip Code</th>
        <th>Country</th>
        <th>Phone</th>
        <th><center>Delete</center></th>
<!--        <th><center>Edit</center></th>-->
    </tr>
<?php foreach($this->data as $d) { ?>
    <tr>
        <input type="hidden" name="id[]" value="<?php echo $d->id ?>" />
        <td><input type="text" name="first_name[]" value="<?php echo $d->first_name; ?>" class="form-control" /></td>
        <td><input type="text" name="last_name[]" value="<?php echo $d->last_name; ?>" class="form-control" /></td>
        <td><input type="text" name="address[]" value="<?php echo $d->address; ?>" class="form-control" /></td>
        <td><input type="text" name="city[]" value="<?php echo $d->city; ?>" class="form-control" /></td>
        <td>
            <select name="state[]" class="form-control">
            <?php foreach ($this->states as $k => $v): ?>
                <option value="<?php echo $v['key']; ?>"><?php echo $v['value']; ?></option>
            <?php endforeach ?>
            </select>
        </td>
        <!-- <td><input type="text" name="state[]" value="<?php// echo $d->state; ?>" class="form-control" /></td> -->
        <td><input type="text" name="zip[]" value="<?php echo $d->zip; ?>" class="form-control" /></td>
        <td><input type="text" name="country[]" value="<?php echo $d->country; ?>" class="form-control" /></td>
        <td><input type="text" name="phone[]" value="<?php echo $d->phone; ?>" class="form-control" /></td>
        <td align="center"><input type="checkbox" name="delete[]" value="<?php echo $d->id ?>" /></td>
<!--        <td align="center"><a href="<?php // echo $this->url(array('controller'=>'shipping','action'=>'edit','id'=>$d->id)); ?>">Edit</a></td>-->
    </tr>
<?php } ?>
    <tr>
        <td colspan="77">
            <input type="submit" value="submit" class="btn btn-primary" />
        </td>
    </tr>
    <tr>
        <td colspan="77"><center><?php echo $this->paginationControl($this->data, 'Elastic', 'pageControlShipping.phtml'); ?></center></td>
    </tr>
</table>
    <input type="hidden" name="pages" value="<?php echo $this->pages ?>" />
    <input type="hidden" name="tab" value="<?php echo $this->tab ?>" />
</form>
<?php } ?>
</div>
</div>
</div>