<div class="col-md-12" style="margin-top:10px">

    <div class="panel panel-default">
        <div class="panel-heading">
            Account Confirmation
        </div>
        <div class="panel-body">
            <center><strong><spam style="color:red; font-size:120%">Your new account has been confirmed. One of our staff will activate it soon. Thank you<spam></strong></center>
        </div>
    </div>
   
</div>