<?php 
$this->layout()->setLayout('second_layout');
?>

<style>
    .labeltd {
        padding-top: 0px;
    }
</style>
<p><span style="color:red; font-size:120%"><?php echo $this->errorMessage; ?></span></p>
<div class="panel panel-primary" style="margin-left: -10px;">
  <div class="panel-heading">Add New Customer Form</div>
  <div class="panel-body">
        <form enctype="application/x-www-form-urlencoded" role="form" class="form-horizontal" action="#" method="post" >
            <table style="clear:both;" border="0" cellpadding="2" width="100%" align="center">
            <tr>
                <td class="labeltd" valign="middle">Company's Name<span style="color:red">*</span></td>
                <td colspan="3" valign="top"><input type="text" name="company" tabindex=1 class="form-control" required /></td>
                <!-- second column -->
                <td class="labeltd" valign="middle">Email<span style="color:red">*</span></td>
                <td valign="top"><input type="text" name="email" class="form-control" tabindex=12 required /></td>
            </tr>
            <tr>
                <td class="labeltd" valign="middle">Company Type<span style="color:red">*</span></td>
                <td colspan="3" valign="top"><input type="text" name="company_type" class="form-control" tabindex=2 required /></td>
                <!-- second column -->
                <td class="labeltd" valign="middle">Phone<span style="color:red">*</span></td>
                <td valign="top"><input type="text" name="phone" class="form-control" tabindex=13 required /></td>
            </tr>
            <tr>
                <td class="labeltd" valign="middle">First Name<span style="color:red">*</span></td>
                <td colspan="3" valign="top"><input type="text" name="first_name" class="form-control" tabindex=3 required /></td>
                <!-- second Column -->
                <td class="labeltd" valign="middle">Fax</td>
                <td valign="top"><input type="text" name="fax" class="form-control" tabindex=14 /></td>
            </tr>
            <tr>
                <td class="labeltd" valign="middle">Last Name<span style="color:red">*</span></td>
                <td colspan="3" valign="top"><input type="text" name="last_name" class="form-control" tabindex=4 required /></td>
                <!-- second column-->
                <td class="labeltd" valign="middle">Website</td>
                <td valign="top"><input type="text" name="website" class="form-control" tabindex=15 /></td>
            </tr>
            <tr>
                <td class="labeltd" valign="middle">Title</td>
                <td colspan="3" valign="top"><input type="text" name="title" class="form-control" tabindex=5 /></td>
                <!-- second column -->
                <td class="labeltd" valign="middle">Tax Id<span style="color:red">*</span></td>
                <td valign="top"><input type="text" name="tax_id" class="form-control" tabindex=16 required /></td>
            </tr>
            <tr>
                <td class="labeltd" valign="middle">Billing Address<span style="color:red">*</span></td>
                <td colspan="3" valign="top"><input type="text" name="address" class="form-control" tabindex=6 required /></td>
                <!-- second column -->
                <td colspan="2" class="labeltd" style="visibility:hidden">Would you like to receive our promotions?</td>
            </tr>
            <tr>
            	<td class="labeltd" valign='middle'>Address 2</td>
            	<td colspan="3" valign="top"><input type="text" name="address2" class="form-control" tabindex="7"></td>
            </tr>
            <tr>
                <td class="labeltd" valign="middle" height="30">City<span style="color:red">*</span></td>
                <td valign="top" height="30"><input type="text" name="city" class="form-control" tabindex=8 required /></td>
                <!-- second column -->
                <td class="labeltd" valign="middle" height="30">State<span style="color:red"></span></td>
                <td valign="top" height="30"><input list="states" name="states" class="form-control" tabindex=9 /><datalist id="states"></datalist></td>
            </tr>
            <tr>
                <td class="labeltd" valign="middle" height="30">Zip Code<span style="color:red">*</span></td>
                <td colspan="1" valign="top"><input type="text" name="zip" class="form-control" tabindex=10 required /></td>
                <!-- second column -->
                <td class="labeltd" valign="middle">Country<span style="color:red">*</span></td>
                <td valign="top">
                	<input list="country" name="country" class="form-control" tabindex=11>
					<datalist id="country"></datalist>
                </td>
            </tr>
            <!-- <tr>
                <td colspan="88"><?php// echo $this->element->getElement('captcha'); ?></td>
            </tr> -->
            <tr>
                <td colspan="88" align="left"><input type="submit" name="Submit" class="btn btn-primary" tabindex=17><input type="reset" name="Reset" class="btn btn-danger" style="margin-left:10px" tabindex=18></td>
            </tr>
        </table>
  </form>
  </div>
 </div>

<script type="text/javascript">
$(window).load(function(){
	getStates();
	getCountries();
});

function getStates() {
	var url = "../../json/states.json";
	var states;

	$.getJSON(url, function(data) {
        $.each(data, function(key, value) {
            states = "<option value=\"" + value + "\">" + key + "</option>";
            $('#states').append(states);
        });
    });
}

function getCountries(){
	var url = "../../json/countries.json";
	var countries;

	$.getJSON(url, function(data) {
        $(data.country).each(function() {
        	countries = "<option value=\"" + this.name + "\">" + this.code + "</option>";   
            $('#country').append(countries);
        });
    });

}

</script>
