<?php 
	$this->layout()->setLayout('second_layout'); 
?>
<div class="panel panel-primary">
	<div class="panel-heading">Change Customer's Password</div>
	<div class="panel-body">
		<form id="form_change_password" method="post" action="<?php echo $this->baseUrl(); ?>/register/changepassword/reg_id/<?php echo $this->id; ?>">
			<label>New Password</label>
			<input type="password" id="pass1" name="pass1" class="form-control input-sm" />
			<label>Type Again The Password</label>
			<input type="password" id="pass2" name="pass2" class="form-control input-sm" />
			<br>
			<input type="submit" class="btn btn-primary">
		</form>
	</div>
<p><center><strong><spam style="color:red;"><?php
if ($this->success != null) {
 	if($this->success){ 
		echo "Password has been changed successfully"; 
	} else { 
		echo "Error changing the password, please contact administrator";
	}
 } 
 ?></spam></strong></center></p>
</div>

<script type="text/javascript">

$( "#form_change_password" ).validate({
  rules: {
    pass1: "required",
    pass2: {
    	required: true,
      	equalTo: "#pass1"
    }
  }
});
</script>