<div class="container" style="width:970px !important; margin: 0 0 0 -15px; padding: 0 0 0 0">
    <div class="col-12">
        <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
          <!-- Indicators -->
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
          </ol>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
          <?php if($this->pic1) { ?>
            <div class="item active">
                <a href="<?php echo $this->link1; ?>" ><img src="<?php echo $this->baseUrl();?>/img/banners/<?php echo $this->pic1?>"></a>
            </div>
          <?php } ?>
          <?php if($this->pic2) { ?>
            <div class="item">
                <a href="<?php echo $this->link2; ?>" ><img src="<?php echo $this->baseUrl();?>/img/banners/<?php echo $this->pic2?>"></a>
            </div>
          <?php } ?>
          <?php if($this->pic3) { ?>
            <div class="item">
                <a href="<?php echo $this->link3; ?>" ><img src="<?php echo $this->baseUrl();?>/img/banners/<?php echo $this->pic3?>"></a>
            </div>
          <?php } ?>
          <?php if($this->pic4) { ?>
            <div class="item">
                <a href="<?php echo $this->link3; ?>" ><img src="<?php echo $this->baseUrl();?>/img/banners/<?php echo $this->pic4?>"></a>
            </div>
          <?php } ?>
          </div>

          <!-- Controls -->
          <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
          </a>
          <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
          </a>
        </div>
    </div>
        <div class="row" style="max-width: 970px; border: 0px solid black; margin-left: auto; margin-right: auto;">
            <div class="col-4 column" style="margin-top: 5px;border: 0px solid black">
                <a href="<?php echo $this->link5; ?>" ><img src="<?php echo $this->baseUrl();?>/img/banners/<?php echo $this->pic5?>"></a>
            </div>
            <div class="col-4 column" style="margin-top: 5px;border: 0px solid black">
                <a href="<?php echo $this->link6; ?>" ><img src="<?php echo $this->baseUrl();?>/img/banners/<?php echo $this->pic6?>" style="padding-left: 25px"></a>
            </div>
            <div class="col-4 column" style="margin-top: 5px; border: 0px solid black">
                <a href="<?php echo $this->link7; ?>" ><img src="<?php echo $this->baseUrl();?>/img/banners/<?php echo $this->pic7?>" style="padding-left: 25px"></a>
            </div>
        </div>
</div>
<br>