 <div class="panel panel-primary">
        <div class="panel-heading">Add New Color Form</div>
        <div class="panel-body">
            <form enctype="application/x-www-form-urlencoded" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
                <table width='100%'>
                    <tr>
                        <td>Color</td>
                        <td><?php echo $this->element->getElement('name'); ?></td>
                    </tr>
                    <tr>
                        <td>Code</td>
                        <td><?php echo $this->element->getElement('code'); ?></td>
                    </tr>
                    <tr>
                        <td>RGB</td>
                        <td><?php echo $this->element->getElement('rgb'); ?></td>
                    </tr>
                     <tr>
                        <td>Sort</td>
                        <td><?php echo $this->element->getElement('sort'); ?></td>
                    </tr>
                    <tr>
                        <td colspan="2"><?php echo $this->element->getElement('submit'); ?><?php echo $this->element->getElement('reset'); ?></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>