 <div class="panel panel-primary">
        <div class="panel-heading">Add New Combo Form</div>
        <div class="panel-body">
            <form enctype="application/x-www-form-urlencoded" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
                <table width='100%'>
                    <tr>
                        <td>Choose Combo</td>
                        <td><?php echo $this->element->getElement('cdetail'); ?></td>
                    </tr>
                    <tr>
                        <td>Products</td>
                        <td><?php echo $this->element->getElement('pro_id'); ?></td>
                    </tr>
                    <tr>
                        <td colspan="2"><?php echo $this->element->getElement('submit'); ?><?php echo $this->element->getElement('reset'); ?></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>