<div class="panel panel-primary">
        <div class="panel-heading">Contact us Form</div>
        <div class="panel-body">
            <form enctype="application/x-www-form-urlencoded" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
                <table width='100%'>
                	<tr>
                		<td>
							Content
                		</td>
                		<td>
                			<?php echo $this->element->getElement('content'); ?>
                		</td>
                	</tr>
                	<tr>
                      <td colspan="2"><?php echo $this->element->getElement('submit'); echo $this->element->getElement('reset'); ?></td>
                	</tr>
                </table>
            </form>
        </div>
</div>