<div class="panel panel-primary">
        <div class="panel-heading">Add New Discount Form</div>
        <div class="panel-body">
            <form enctype="application/x-www-form-urlencoded" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
                <table width='100%'>
                    <tr>
                        <td>Code</td>
                        <td><?php echo $this->element->getElement('code'); ?></td>
                    </tr>
                    <tr>
                        <td>Description</td>
                        <td><?php echo $this->element->getElement('description'); ?></td>
                    </tr>
                    <tr>
                        <td>Initial Date</td>
                        <td><?php echo $this->element->getElement('init_date'); ?></td>
                    </tr>
                    <tr>
                        <td>End Date</td>
                        <td><?php echo $this->element->getElement('end_date'); ?></td>
                    </tr>
                    <tr>
                        <td>Status</td>
                        <td><?php echo $this->element->getElement('status'); ?></td>
                    </tr>
                     <tr>
                        <td>Stackable</td>
                        <td><?php echo $this->element->getElement('stackable'); ?> Disabling will prevent discount from being applied to already discounted items!</td>
                    </tr>
                    <tr>
                        <td>Minimum Purchase</td>
                        <td><?php echo $this->element->getElement('min_purchase'); ?></td>
                    </tr>
                    <tr>
                        <td>Minimum Quantity</td>
                        <td><?php echo $this->element->getElement('min_quantity'); ?></td>
                    </tr>
                    <tr>
                        <td>Sub-Category</td>
                        <td><?php echo $this->element->getElement('subcat_id'); ?></td>
                    </tr>
                    <tr>
                        <td>Product</td>
                        <td><?php echo $this->element->getElement('pro_id'); ?></td>
                    </tr>
                    <tr>
                        <td>Discount Percentage</td>
                        <td><?php echo $this->element->getElement('percentage'); ?></td>
                    </tr>
                    <tr>
                        <td>Discount Amount</td>
                        <td><?php echo $this->element->getElement('amount'); ?></td>
                    </tr>
                    <tr>
                        <td colspan="2"><?php echo $this->element->getElement('Submit'); ?><?php echo $this->element->getElement('Reset'); ?></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>