<div class="panel panel-default">
    <div class="panel-heading">Home Button Banner - Image Size:<span style="color: red"> 260w x 100h</span></div>
        <div class="panel-body">
            <form enctype="multipart/form-data" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
                <table width='100%'>
                    <tr>
                        <td><?php echo $this->element->getElement('banner'); ?></td>
                        <td width="25%"><?php echo $this->element->getElement('link'); ?></td>
                        <td><?php echo $this->element->getElement('position'); ?></td>
                        <td><?php echo $this->element->getElement('submit'); ?></td>
                        <td><?php echo $this->element->getElement('reset'); ?></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>