<div class="panel panel-default">
    <div class="panel-heading">Home Page Sliding Images - Image Size: <span style="color: red">940w x 490h</span></div>
        <div class="panel-body">
            <form enctype="multipart/form-data" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
                <table width='100%'>
                    <tr>
                        <td><?php echo $this->element->getElement('banner'); ?></td>
                        <td width="25%"><?php echo $this->element->getElement('link'); ?></td>
                        <td><?php echo $this->element->getElement('sort'); ?></td>
                        <td><?php echo $this->element->getElement('submit'); ?></td>
                        <td><?php echo $this->element->getElement('reset'); ?></td>
                    </tr>
                </table>
            </form>
    </div>
</div>