<div class="panel panel-primary">
    <div class="panel-heading">Import from Sage: <span style="color:red">CSV file only</span></div>
    <div class="panel-body">
        <form enctype="<?php echo $this->element->getAttrib('enctype'); ?>" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
            <table width="100%">
                <tr>
                    <td>File Name (single)</td>
                    <td><?php echo $this->element->getElement('filename'); ?></td>
                </tr>
                <tr>
                    <td colspan="2"><?php echo $this->element->getElement('submit'); ?></td>
                </tr>
            </table>
        </form>
    </div>
</div>
