 <div class="panel panel-default">
        <div class="panel-heading">Add Products to Mail</div>
        <div class="panel-body">
            <form enctype="application/x-www-form-urlencoded" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
                <table style="clear:both" border="0" cellpadding="5" padding="10" width='100%'>
                    <tr>
                        <td>Choose Products</td>
                        <td><?php echo $this->element->getElement('pro_id'); ?></td>
                    </tr>
                    <tr>
                        <td colspan="2"><?php echo $this->element->getElement('submit'); ?><?php echo $this->element->getElement('reset'); ?></td>
                    </tr>
                </table>
            </form>
        </div>
    </div>