<?php if ($this->pageCount): ?>
<ul class="pagination pagination-sm">
<!-- First page link -->
<?php if (isset($this->previous)): ?>
<li>
  <a href="<?php echo $this->url(array('page' => $this->first)); ?>">
    First
  </a>
</li>
<?php else: ?>
<li class="disabled">
  <span class="disabled">First</span>
</li>
<?php endif; ?>
 
<!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<li>
  <a href="<?php echo $this->url(array('page' => $this->previous)); ?>">
    Previous
  </a>
</li>
<?php else: ?>
<li class="disabled">
  <span class="disabled">Previous</span>
</li>
<?php endif; ?>
  
  <!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
  <li>
    <a href="<?php echo $this->url(array('page' => $page)); ?>">
        <?php echo $page; ?>
    </a>
  <li>
  <?php else: ?>
  <li class="active">
    <a href="">
        <?php echo $page; ?>
    </a>
  </li>
  <?php endif; ?>
<?php endforeach; ?>
  
<!-- Next page link -->
<?php if (isset($this->next)): ?>
<li>
  <a href="<?php echo $this->url(array('page' => $this->next)); ?>">
    Next
  </a>
</li>
<?php else: ?>
<li class="disabled">
  <span class="disabled">Next</span>
</li>
<?php endif; ?>
 
<!-- Last page link -->
<?php if (isset($this->next)): ?>
<li>
  <a href="<?php echo $this->url(array('page' => $this->last)); ?>">
    Last
  </a>
</li>
<?php else: ?>
<li class="disabled">
  <span class="disabled">Last</span>
</li>
<?php endif; ?>
 
</ul>

<?php endif; ?>
