<div class="panel panel-primary">
  <div class="panel-heading">Add New Sub-Categories Form</div>
  <div class="panel-body">
        <form enctype="application/x-www-form-urlencoded" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
            <table style="clear:both;" border="0" cellpadding="5px" padding="0" width="100%">
            <tr>
                <td>Sub-Categories</td>
                <td><?php echo $this->element->getElement('subcat_id'); ?></td>
            </tr>
            <tr>
                <td colspan="2"><?php echo $this->element->getElement('csrf'); ?></td>
            </tr>
            <tr>
                
                <td colspan="2"><?php echo $this->element->getElement('Submit'); ?><?php echo $this->element->getElement('Reset'); ?></td>
                
            </tr>
        </table>
  </form>
  </div>
 </div>