<style>
    table {
        clear: both;
        border-collapse: collapse;
    }
    td {
        padding: 10px;
    }
</style>

<div class="panel panel-primary">
  <div class="panel-heading">Add New Product Form</div>
  <div class="panel-body">
        <form enctype="application/x-www-form-urlencoded" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
            <table>
            <tr>
                <td>Product Name</td>
                <td><?php echo $this->element->getElement('name'); ?></td>
            </tr>
            <tr>
                <td>Product Id</td>
                <td><?php echo $this->element->getElement('product_id'); ?></td>
            </tr>
            <tr>
                <td>Product Description</td>
                <td><?php echo $this->element->getElement('description'); ?></td>
            </tr>
            <tr>
                <td>Second Product Description</td>
                <td><?php echo $this->element->getElement('sec_description'); ?></td>
            </tr>
            <tr>
                <td>Dogo Pet URL</td>
                <td><?php echo $this->element->getElement('dogopet_url'); ?></td>
            </tr>
            <tr>
                <td>Expiration Date</td>
                <td><?php echo $this->element->getElement('expires'); ?></td>
            </tr>
            <tr>
                <td>Retail Price</td>
                <td><?php echo $this->element->getElement('r_price'); ?></td>
            </tr>
            <tr>
                <td>Wholesale Price</td>
                <td><?php echo $this->element->getElement('w_price'); ?></td>
            </tr>
            <tr>
                <td>On Sale Price</td>
                <td><?php echo $this->element->getElement('o_price'); ?></td>
            </tr>
            <tr>
                <td>Active</td>
                <td><?php echo $this->element->getElement('active'); ?></td>
            </tr>
            <tr>
                <td>New</td>
                <td><?php echo $this->element->getElement('new'); ?></td>
            </tr>
            <tr>
                <td>Pre-Order</td>
                <td><?php echo $this->element->getElement('pre_order'); ?></td>
            </tr>
            <tr>
                <td width="18%">On_Sale</td>
                <td><?php echo $this->element->getElement('on_sale'); ?></td>
            </tr>
            <tr>
                
                <td colspan="2"><?php echo $this->element->getElement('Submit'); ?><?php echo $this->element->getElement('Reset'); ?></td>
                
            </tr>
        </table>
  </form>
  </div>
 </div>