<div class="panel panel-primary">
    <div class="panel-heading">Add New Image Form - Image Size: <span style="color:red">600w x 600h (px)</span></div>
    <div class="panel-body">
        <form enctype="<?php echo $this->element->getAttrib('enctype'); ?>" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
            <table width="100%">
                <tr>
                    <td>Color</td>
                    <td><?php echo $this->element->getElement('c_id'); ?></td>
                </tr>
                <tr>
                    <td>File Name (multiple)</td>
                    <td><?php echo $this->element->getElement('file'); ?></td>
                </tr>
                <tr>
                    <td colspan="2"><?php echo $this->element->getElement('submit'); ?><?php echo $this->element->getElement('reset'); ?></td>
                </tr>
            </table>
        </form>
    </div>
</div>