<style>
    .labeltd {
        padding-top: 0px;
    }
</style>
<div class="panel panel-default" style="margin-left: -10px;">
  <div class="panel-heading">Register Form</div>
  <div class="panel-body">
        <form enctype="application/x-www-form-urlencoded" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
            <table style="clear:both;" border="0" cellpadding="2" width="100%" align="center">
            <tr>
                <td class="labeltd" valign="top">Company's Name<span style="color:red">*</span></td>
                <td colspan="3" valign="top"><?php echo $this->element->getElement('company'); ?></td>
                <!-- second column -->
                <td class="labeltd" valign="top">Email<span style="color:red">*</span></td>
                <td valign="top"><?php echo $this->element->getElement('email'); ?></td>
            </tr>
            <tr>
                <td class="labeltd" valign="top">Company Type<span style="color:red">*</span></td>
                <td colspan="3" valign="top"><?php echo $this->element->getElement('company_type'); ?></td>
                <!-- second column -->
                <td class="labeltd" valign="top">Phone<span style="color:red">*</span></td>
                <td valign="top"><?php echo $this->element->getElement('phone'); ?></td>
            </tr>
            <tr>
                <td class="labeltd" valign="top">First Name<span style="color:red">*</span></td>
                <td colspan="3" valign="top"><?php echo $this->element->getElement('first_name'); ?></td>
                <!-- second Column -->
                <td class="labeltd" valign="top">Fax</td>
                <td valign="top"><?php echo $this->element->getElement('fax'); ?></td>
            </tr>
            <tr>
                <td class="labeltd" valign="top">Last Name<span style="color:red">*</span></td>
                <td colspan="3" valign="top"><?php echo $this->element->getElement('last_name'); ?></td>
                <!-- second column-->
                <td class="labeltd" valign="top">Website</td>
                <td valign="top"><?php echo $this->element->getElement('website'); ?></td>
            </tr>
            <tr>
                <td class="labeltd" valign="top">Title</td>
                <td colspan="3" valign="top"><?php echo $this->element->getElement('title'); ?></td>
                <!-- second column -->
                <td class="labeltd" valign="top">Tax Id<span style="color:red">*</span></td>
                <td valign="top"><?php echo $this->element->getElement('tax_id'); ?></td>
            </tr>
            <tr>
                <td class="labeltd" valign="top">Billing Address<span style="color:red">*</span></td>
                <td colspan="3" valign="top"><?php echo $this->element->getElement('address'); ?></td>
                <!-- second column -->
                <td colspan="2" class="labeltd" style="visibility:hidden">Would you like to receive our promotions?<?php echo $this->element->getElement('spam'); ?></td>
            </tr>
            <tr>
                <td class="labeltd" valign="top">Billing Address 2<span style="color:red"></span></td>
                <td colspan="3" valign="top"><?php echo $this->element->getElement('address2'); ?></td>
            </tr>
            <tr>
                <td class="labeltd" valign="top" height="30">City<span style="color:red">*</span></td>
                <td valign="top" height="30"><?php echo $this->element->getElement('city'); ?></td>
                <!-- second column -->
                <td class="labeltd" valign="top" height="30">State<span style="color:red"></span></td>
                <td valign="top" height="30"><?php echo $this->element->getElement('state'); ?></td>
            </tr>
            <tr>
                <td class="labeltd" valign="top" height="30">Zip Code<span style="color:red">*</span></td>
                <td colspan="1" valign="top"><?php echo $this->element->getElement('zip'); ?></td>
                <!-- second column -->
                <td class="labeltd" valign="top">Country<span style="color:red">*</span></td>
                <td valign="top"><?php echo $this->element->getElement('country'); ?></td>
            </tr>
            <tr>
                <!-- first column -->
                <td></td>
                <td></td>
                <!-- second column -->
                <td class="labeltd" valign="top">Not USA</td>
                <td valign="top"><?php echo $this->element->getElement('other_country') ?></td>
            </tr>
            <tr>
                <td colspan="88"><?php echo $this->element->getElement('captcha'); ?></td>
            </tr>
            <tr>
                <td colspan="88" align="left"><?php echo $this->element->getElement('Send'); ?><?php echo $this->element->getElement('Reset'); ?></td>
            </tr>
        </table>
  </form>
  </div>
 </div>