<div class="col-md-8"> 
<div class="panel panel-primary">
        <div class="panel-heading">Add New Store Form</div>
        <div class="panel-body">
            <form enctype="application/x-www-form-urlencoded" role="form" class="form-horizontal" action="<?php echo $this->element->getAction(); ?>" method="post" >
                <table width='100%'>
                    <tr>
                        <td>Store Name</td>
                        <td><?php echo $this->element->getElement('name'); ?></td>
                    </tr>
                    <tr>
                        <td>Currently active?</td>
                        <td><?php echo $this->element->getElement('active'); ?></td>
                    </tr>
                    <tr>
                        <td>Store's Address</td>
                        <td><?php echo $this->element->getElement('address'); ?></td>
                    </tr>
                    <tr>
                        <td>City</td>
                        <td><?php echo $this->element->getElement('city'); ?></td>
                    </tr>
                    <tr>
                        <td>State</td>
                        <td><?php echo $this->element->getElement('state'); ?></td>
                    </tr>
                    <tr>
                        <td>Country</td>
                        <td><?php echo $this->element->getElement('country'); ?></td>
                    </tr>
                    <tr>
                        <td>Zip Code</td>
                        <td><?php echo $this->element->getElement('zip_code'); ?></td>
                    </tr>
                    <tr>
                        <td>Latitude/Longitude</td>
                        <td><?php echo $this->element->getElement('latlng'); ?></td>
                    </tr>
                    <tr>
                        <td>Website</td>
                        <td><?php echo $this->element->getElement('website'); ?></td>
                    </tr>
                    <tr>
                        <td colspan="2"><?php echo $this->element->getElement('submit'); ?><?php echo $this->element->getElement('reset'); ?></td>
                    </tr>
                </table>
            </form>
        </div>
</div>
</div>