<form action="<?php echo $this->baseUrl(); ?>/subcategories/delete" method="post" onsubmit="return confirm('Are you sure you want to submit this form?');">
    <table width='100%' >
        <thead>
        <tr>
            <th><center>Description</center></th>
            <th><center>Sort</center></th>
            <th><center>Delete</center></th>
        </tr>
    </thead>
    <tbody>
<?php foreach ($this->subcategories as $sub) { ?>
        <input type="hidden" name="id[]" value="<?php echo $sub->id?>" />
<tr>
    <td align="center"><input type="text" class="form-control" size="15" name="name[]" value="<?php echo $sub->name ?>" /></td>
    <td align="center"><input type="text" class="form-control" size="1" name="sort[]" value="<?php echo $sub->sort ?>" /></td>
    <td align="center"><input type="checkbox" name="delete[]" value="<?php echo $sub->id ?>" /></td>
</tr>
<?php } ?>
</tbody>
</table>
    <br>
    <input type="submit" class="btn btn-primary" value="Submit" />
</form>