<?php
$this->layout()->setLayout('second_layout');
?>
<div class="panel panel-primary">
<div class="panel-heading">List of Product Images</div>
<div class="panel-body">
    <?php
    if (sizeof($this->pictures) > 0) { ?>
        <form action=<?php echo $this->baseUrl() . "/proimages/update" ?> method="post" onsubmit="return confirm('Are you sure you want to submit this form?');">
        <table style="width: 100%">
            <thead>

                <tr>
                    <th><center>Color</center></th>
                    <th><center>File Name</center></th>
        <th><a href="<?php echo $this->url(array('controller' => 'products', 'action' => 'detail', 'tab'=>'image', 'sort' => 'sort')); ?>"><center>Sort</center></a></th>
                    <th><center>Created</center></th>
                    <th><center>Delete</center></th>
            </tr>
            </thead>
            <tfoot>
                <tr>
                    <td colspan="5"><center><?php echo $this->paginationControl($this->pictures, 'Elastic', 'pagecontrol.phtml'); ?></center></td>
            </tr>
            </tfoot>
            <tbody>
                <?php foreach ($this->pictures as $picture) { ?>
                    <tr>
                <input type="hidden" name="pic_id[]" id="pic_id" value="<?php echo $picture->id ?>" />
                <td align="center" width="20%"><?php echo $this->formSelect('colors[]', $picture->c_id, array('size' => 1, 'class' => 'form-control', 'multiple' => false), $this->colors); ?></td>
                <td align="center"><img src="<?php echo Zend_Controller_Front::getInstance()->getBaseUrl() . '/products_thu/' . $picture->name; ?>" width="100" height="100" class="img-circle" /><?php echo $this->formText('names[]', $picture->name, array('hidden' => TRUE)); ?></td>
                <td align="center" width="10%"><?php echo $this->formText('sort[]', $picture->sort, array('size' => 1, 'class' => 'form-control')); ?></td>
                <td align="center"><?php echo $picture->created; ?></td>                  
                <td align="center"><?php echo $this->formCheckbox('delete[]', $picture->id, array('checked' => FALSE)); ?></td>
                </tr>
            <?php } ?>
            <tr>
                <td colspan="5"><?php echo $this->formSubmit('submit', 'Submit', array('class' => 'btn btn-primary')) ?></td>
            </tr>
            </tbody>
        </table>
        <input type="hidden" name="pro_id" value="<?php echo $this->id; ?>" />
        <input type="hidden" name="page" value="<?php echo $this->page; ?>" />
    </form>
    <?php } ?>
</div>
</div>