<div class="container-fluid">
<div class="col-md-12">
    <div class="jumbotron">
      <h1>Thank you!</h1>
      <p>Your business is much appreciated, and we will do our very best to continue to meet your orders needs.</p>
      <p>Your continued patronage and suggestions are a vital part of our growth. And for that, we are most grateful.</p>
      <p>Thanks again! We look forward to serving you for many years to come.</p>
      <p><a href="<?php echo $this->baseUrl()?>/home/contactus" class="btn btn-primary btn-lg" role="button">Contact Us</a></p>
    </div>
</div>
</div>