<?php echo $this->doctype(); ?>
<html>
<head>
<?php $this->headTitle()->append('Register');?>
<?php echo $this->headTitle();?>
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/site.css'); ?>
<?php $this->headLink()->appendStylesheet($this->baseUrl().'/css/navigation.css'); ?>
<?php echo $this->headLink()->prependStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.min.css'); ?>
<?php echo $this->headScript()->appendFile('//netdna.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.min.js');?>
<?php echo $this->jQuery();?>
<?php 
    if ( $this->ckeditor ) { 
        echo $this->headScript()->appendFile( $this->baseUrl().'/js/ckeditor/ckeditor.js');
    }
?>
</head>
<body>
<?php //echo $this->layout()->content ?>
<div id="wrapper">
        <div id="header">Dogo Design -- <?php if(Zend_Auth::getInstance()->hasIdentity()){echo "Welcome: ".Zend_Auth::getInstance()->getIdentity()->username;} ?></div>
	<div id="content">
		<div id="sidebar">
			<ul>
                            <?php echo $this->navigation(); ?>
			</ul>
			<ul>
                            <?php
                                    echo $this->action('list','categories',null,array());
                            ?>
			</ul>
		</div>
		<div id="slideshow">
		<?php
			if($this->banners){
                            foreach ($this->banners as $banner) {
                                    echo "<img src=".$this->baseUrl().'/img/banners/'.$banner['path']." />";
                            }
		 	}
	 	?>
		</div>
		<div id="main_content">
			<?php echo $this->layout()->content ?>
		</div>
	</div>
	<div id="footer">footer</div>
</div>

</body>
</html>