<?php echo $this->doctype(); ?>
<head>
    <?php $this->headTitle()->append('Register'); ?>
    <?php echo $this->headTitle('Admin'); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl() . '/css/site.css'); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl() . '/css/navigation.css'); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl() . '/css/tablestyle.css'); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl() . '/css/jquery-ui-1.10.4.custom.min.css'); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl() . '/css/bootstrap.min.css'); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl() . '/css/bootstrap-theme.min.css'); ?>
    <?php $this->headLink()->prependStylesheet($this->baseUrl() . '/css/colpick.css'); ?>

    <?php $this->headScript()->appendFile('http://maps.google.com/maps/api/js?sensor=true'); ?>
    <?php $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-1.10.2.js'); ?>
    <?php $this->headScript()->appendFile($this->baseUrl() . '/js/jquery-ui-1.10.4.custom.min.js'); ?>
    <?php $this->headScript()->appendFile($this->baseUrl() . '/js/colpick.js'); ?>
    <?php $this->headScript()->appendFile($this->baseUrl() . '/js/jquery.ui.map.full.min.js'); ?>
    <!-- validation plugin -->
    <?php $this->headScript()->appendFile('http://jqueryvalidation.org/files/dist/jquery.validate.min.js'); ?>
    <?php $this->headScript()->appendFile('http://jqueryvalidation.org/files/dist/additional-methods.min.js'); ?>
    <?php
    echo $this->headScript();
    echo $this->headLink();
    ?>
    <?php echo $this->headScript()->appendFile($this->baseUrl() . '/js/bootstrap.min.js'); ?>
</head>
<style>
    body {border:0px solid black; margin:0 auto; width:100%; background:#fff; word-wrap:break-word;}

    #header {background:#FFF; border-bottom: 0px solid #ccc; min-height: 0px}

    #outer1 {float:left; width:15%; background:#FFF;}
    #outer2 {float:left; width:70%; background:#FFF;}
    #outer3 {float:right; width:15%; background:#FFF;}
    #outer1, #outer2, #outer3 {padding-bottom:32767px; margin-bottom:-32767px;}

    #wrapper {overflow: hidden; background:#fff; width: 100%}


    #footer {clear:both; background:#fff; min-height: 50px}

    h1 {font-size:20px; margin:0; padding:10px 0; color:#fff;}
    h3 {font-size:18px; margin:0; padding:8px 0;}
    .content {padding:10px;}
    p {font-size:12px; line-height:1.5em; margin:0; padding:5px 0;}
    #footer p,
    #header p {color:#fff;}
    #footer a {color:#fff;}
    #footer a:hover {text-decoration:none;}
    .menu ul {position:relative; float: left; list-style-type: none; margin: 0; padding: 0}
    .menu li {display: inline-block; margin-left: 15px}
    .menu {position:relative; float:left; left:100px; top: 50px}
</style>
<!-- Color Picker style and script -->

<!--[if lte IE 7]>
<style type="text/css">
body {word-wrap:break-word;}
#outer2 {float:left; width:59.8%; background:#c0c0c0;}

/* for IE6 */
* html #wrapper {display:inline-block;}
</style>
<![endif]-->

</head>
<body>
    <div id="header">

    </div> <!-- end header -->

    <div id="wrapper">
<!--         <div id="outer1">
            <div class="content">

            </div>
        </div>
 -->

        <div id="outer2_1">
            <div class="col-md-12" style="margin-top:20px;">
                <?php echo $this->layout()->content; ?>
            </div> <!-- end content -->
        </div> <!-- end outer2 -->


 <!--        <div id="outer3">
            <div class="content">

            </div> 
        </div>
 -->


    </div><!-- end #wrapper -->

    <div id="footer">
        <div class="content">
            
        </div>
    </div> <!-- end footer -->
</body>
</html>
