<?php $this->layout()->setLayout('second_layout');

?>

<script>
    $(document).ready(function(){        
       $('#init_date').datepicker({dateFormat:'yy-mm-dd'}); 
       $('#end_date').datepicker({dateFormat:'yy-mm-dd'}); 
       
       getProducts(<?php echo $this->subcat_id ?>);
    });
    
    function getProducts(subcat_id){
        $pro_id = $('#pro_id');
        
        $url = "<?php echo $this->baseUrl();?>/products/getproducts";
     //   console.log($url);
        $.ajax({url:$url,data:{'subcat_id':subcat_id,'pro_id':<?php echo $this->pro_id?>},success:function(data){$pro_id.html(''); $pro_id.append(data);}});
    }
</script>

<?php
$this->form->setAction($this->url(array('controller'=>'discounts','action'=>'update')));
echo $this->form;