<?php 
$this->layout()->setLayout('second_layout');
$this->ckeditor = 'ckeditor';
?>

<form action="<?php echo $this->baseUrl(); ?>/sizes/changemsg" method="post">
	<div class="form-group">
		<label for="description">Description</label>
		<textarea name="description">
			<?php echo $this->message->description; ?>
		</textarea>
	</div>
	<div class="form-group">
		<input type="submit" name="Submit" class="btn btn-primary" />
	</div>
</form>

<?php echo $this->setupEditor('description'); ?>