<?php
$this->layout()->setLayout('second_layout');
echo $this->errormessage;
echo $this->form;
?>
<div class="panel panel-primary">
<div class="panel-heading">List of Payment Methods</div>
<div class="panel-body">
<table class="table table-hover">
    <thead>
        <tr>
            <th>Payment Method</th>
            <th>More Info</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($this->data as $d){ ?>
        <tr>
            <td><?php echo $d->name; ?></td>
            <td><?php echo $d->extra; ?></td>
            <td><a href="<?php echo $this->url(array('controller'=>'paymentmethods','action'=>'delete','id'=>$d->id)); ?>">Delete</a></td>
        </tr>
        <?php } ?>
    </tbody>
</table>
</div>
</div>