    <div class="well col-md-12" style="width: 940px; margin-left: 0px; margin-top: 15px">
        <div class="col-md-7">
            <p>
                <?php echo $this->about[0]->aboutus; ?>
                <!-- <a href="<?php //echo $this->baseUrl()?>/home/contactus">contact us</a>. -->
            </p>
        </div>
        <div class="col-md-5">
            <img src="<?php echo $this->baseUrl()?>/img/banners/aboutus.jpg" />
        </div>
    </div>