<script>
 $(document).ready(function(){
        address = '4402 11th St. STE 508 LIC, NY 11101';
        $('#map_canvas').gmap('search', { 'address': address }, function(results,isFound) {
            if (isFound) {
                $('#map_canvas').gmap('get','map').panTo(results[0].geometry.location);
                $('#map_canvas').gmap('option', 'zoom', 14);
            }
        });
        addmarker();
});

function addmarker(){
    long = '40.749647, -73.949536';
    $('#map_canvas').gmap('addMarker', {'position': long, 'bounds': true}).click(function() {
                $('#map_canvas').gmap('openInfoWindow', {'content': 'Dogo'}, this);
    });
}

</script>

<div class="well col-md-12" style="width: 940px; margin-left: 0px; margin-top: 15px;">
<div class="col-md-6">
    <?php echo $this->about[0]->address; ?> 
</div>
    <div class="col-md-6">
            <div id="map_canvas" style="width:100%;height:300px"></div>
        </div>
</div>