<style type="text/css">
    tr.top td { border-top: thin solid black; }
    tr.bottom td { border-bottom: thin solid black; }
    tr.row td:first-child { border-left: thin solid black; }
    tr.row td:last-child { border-right: thin solid black; }
</style>

<div class="col-md-12" style="width: 940px; margin-left: 0px; margin-top: 15px;">
    <div style="text-align: center">
        <img src="<?php echo $this->baseUrl()?>/img/sizechart.jpg"><br><br>
    </div>
    <p style="text-align: left">
        <?php echo $this->message->description; ?>
    </p>
</div>
   
<div style="clear:both; width: 100%">
<?php foreach ($this->cat as $k => $v) { ?>
    <div style="position:relative; float:left; border:1px solid #fcabcb; margin-right: 5px; margin-top: 5px;">
        <div style="position:relative; float: left; width:100%; height: 300px">
            <table cellpadding="5" cellspacing="5">
                    <tr>
                        <td colspan="99" style="background-color: #fcabcb; color: white"><?= $v->name; ?></td>
                    </tr>
                    <tr>
                        <td rowspan="2"></td>
                        <?php if($v->length){echo "<td colspan=2 align=center>Length</td>";} ?>
                        <?php if($v->neck){echo "<td colspan=2 align=center>Neck</td>";} ?>
                        <?php if($v->girth){echo "<td colspan=2 align=center>Girth</td>";} ?>
                        <?php if($v->width){echo "<td colspan=2 align=center>Width</td>";} ?>
                    </tr>
                    <tr>
                        <?php if($v->length){echo "<td align=center>cm</td><td align=center>inch</td>";} ?>
                        <?php if($v->neck){echo "<td align=center>cm</td><td align=center>inch</td>";} ?>
                        <?php if($v->girth){echo "<td align=center>cm</td><td align=center>inch</td>";} ?>
                        <?php if($v->width){echo "<td align=center>cm</td><td align=center>inch</td>";} ?>
                    </tr>
                    <?php foreach ($this->data as $d): ?>
                        <?php if(strcmp($v->name, $d->cat_name)==0){ ?>
                        <tr>
                            <td><?php echo $d->size; ?></td>
                            <?php if($v->length){echo "<td align=center>".$d->length_cm."</td><td align=center>".$d->length_in."</td>";} ?>
                            <?php if($v->neck){echo "<td align=center>".$d->neck_cm."</td><td align=center>".$d->neck_in."</td>";} ?>
                            <?php if($v->girth){echo "<td align=center>".$d->girth_cm."</td><td align=center>".$d->girth_in."</td>";} ?>
                            <?php if($v->width){echo "<td align=center>".$d->width_cm."</td><td align=center>".$d->width_in."</td>";} ?>
                        </tr>
                    <?php } ?>
                    <?php endforeach ?>
                </table>
        </div>
    </div>
<?php } ?>
</div>

<div style="position:relative; float:left; width: 100%; height: 25px;"></div>